### ISSUE TITLE
Literadio 1 and Cetus lite issues

### ISSUE THREAD

**Issue by shash-what** [BETAFPV/BETAFPV_Configurator#35]
The drone drifts right out of the box even after calibration attempts. The gyro movement doesn't reflect in the configurator. And now after trying to offset the right roll on the controller to compensate, the bindings have all gone awry. It was a mode 2 (left joystick throttle) which now has throttle on the right stick, pitch on right stick roll axis, and roll or yaw don't exist anymore. Is there anyway to reverse this action by flashing OG firmware? Have tried all setting and factory reset in Configurator with no results.

**Comment by LeehotYuu** [comment]
This issue is long gone and maybe my reply is no longer helpful, but I try to make some explanations and then close this issue.
There was an error in the previous Restore Factory Settings function, the default blend control settings were:
CH1=Roll (A); weight=100; offset=0;
CH2=Pitch (E); 100; 0;
CH3=Throttle (T); 100; 0;
CH4=Yaw (R); 100; 0;
CH5=SA; 100; 0;
CH6=SB; 100; 0;
CH7=SC; 100; 0;
CH8=SD; 100; 0;
Click the “Save and Restart” button.

If there is a binding error, check if the built-in RF module protocol has been modified, it depends on the drone, usually Frsky_D8.
Refreshing the firmware cannot erase this data as it represents the user's personal usage habits.
