### ISSUE TITLE
Missing Mac & Linux versions

### ISSUE THREAD

**Issue by zendes** [BETAFPV/BETAFPV_Configurator#46]
RC1 of the configurator has a note saying "stay tuned for the mac & linux versions". It's been about 6 months since that version was posted. Do you have an ETA for when those versions will be available?

**Comment by contre95** [comment]
I support your claim but this is Chinese, they don't Linux for things.

**Comment by KennethWilke** [comment]
I got the literadio 3 assuming it had this :\

**Comment by YonatanSimson** [comment]
When do intend to add linux version?
Can I compile the code myself and launch in linux?

**Comment by LeehotYuu** [comment]
BETAFPV Configurator for Linux (Debian family) platform has been released.
Please read the Linux-related installation instructions in the user's manual, as well as the FAQ.
https://support.betafpv.com/hc/en-us/articles/40712112687769-BETAFPV-Configurator-User-Manual

Don't run this code now because it hasn't been updated completely.
