### ISSUE TITLE
I can't install the firmware using the configurator 

### ISSUE THREAD

**Issue by K2AAE** [BETAFPV/BETAFPV_Configurator#55]
When I try to install the 'latest' firmware with the latest Configurator the Select radio and Select firmware boxes show Loading...... forever.
After waiting for a reply from 'support' I tried to use the LiteRadio 3 as a joystick, nope, it is configured as a COM device NOT HID. The manual talks about installing a driver but WHAT DRIVER?
After two years of ownership I'd like to use this device.

**Comment by LeehotYuu** [comment]
> When I try to install the 'latest' firmware with the latest Configurator the Select radio and Select firmware boxes show Loading...... forever. After waiting for a reply from 'support' I tried to use the LiteRadio 3 as a joystick, nope, it is configured as a COM device NOT HID. The manual talks about installing a driver but WHAT DRIVER? After two years of ownership I'd like to use this device.

What? Two years! Well, the fact is that the online way of updating the firmware we have suspended the maintenance because of regional restrictions. It's really a handy feature.

For the driver, there is usually no driver required and nothing to worry about at all, unless your USB itself is not working properly.

If you want to update the firmware you can download it from the betafpv website and then use the local update method in BETAFPV Configurator:
LR3 (Frsky/ELRS).
https://support.betafpv.com/hc/en-us/articles/4414348993177-Lite-Radio-3

Finally, we've wrapped up the last test of BETAFPV Configurator (although there are still some issues that are hard to fix on the linux platform), and I expect to release it to github this week, and this update no longer needs to differentiate between using HID or COM for the remote control.

Translated with DeepL.com (free version)

**Comment by askrinnik** [comment]
> For the driver, there is usually no driver required and nothing to worry about at all, unless your USB itself is not working properly.
> 
> If you want to update the firmware you can download it from the betafpv website and then use the local update method in

Connecting the LiteRadio 3 to a laptop with an AMD processor is still a big issue :(

**Comment by LeehotYuu** [comment]
> > For the driver, there is usually no driver required and nothing to worry about at all, unless your USB itself is not working properly.
> > If you want to update the firmware you can download it from the betafpv website and then use the local update method in
> 
> Connecting the LiteRadio 3 to a laptop with an AMD processor is still a big issue :(

I fixed the AMD recognition bug in July this year, maybe your firmware version has not been upgraded? And I recommend you to use the recently released firmware (24_11_08), many bugs may have been fixed long ago in the new firmware.
In addition to that, some support has been added for FPV simulators, such as:
* Can be detected by FPV simulators on Android devices (if your Android supports OTG);
* Being used as an x360 joystick.

Since the online update firmware has not been maintained for a long time, the new firmware needs to be obtained from the betafpv website.
