### ISSUE TITLE
How to configure the LiteRadio 2 SE Frisky

### ISSUE THREAD

**Issue by R-Ladig** [BETAFPV/BETAFPV_Configurator#8]
Sooo... LiteRadio 2 and 3 can be configured with OpenTx; LiteRadio 2 SE ELRS with this app... 
Is there a plan to make it compatible with the Frisky version or is there any other idea how to configure the sticks?

**Comment by HWT662988** [comment]
There is a new board name"**LiteRadio 2 SE V2 Frisky** " which was released recently.is support for using  this Configurator later than 1.1.0-RC1.
But unfortunately, the old board named"**LiteRadio 2 SE Frisky**" which released in 2020 is no compatible with now,because they use different board and code frameworks .maybe I'll try to rewrite the old code  to make it be compatibility, but It takes a lot of work to do.So if i could make it work properly,i will release it and infrom you .
